apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: checkout-api-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: checkout-api
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: data-services
